### ISSUE TITLE
Could you provide the files './icd9to10.csv' and  './data/processed_dip.pkl' ?

### ISSUE THREAD

**Issue by bulbyang** [The-Real-JerryChen/TRANS#1]
![image](https://github.com/The-Real-JerryChen/TRANS/assets/44968049/bda9e0c1-2202-482c-8f87-34b0b1597d80)
![image](https://github.com/The-Real-JerryChen/TRANS/assets/44968049/dd39835f-7093-4734-92f0-bfb0b43bb8fe)

**Comment by The-Real-JerryChen** [comment]
Hi, I've uploaded the icd9to10.csv in [link](https://github.com/The-Real-JerryChen/TRANS/tree/main/data). For the CCAE data file, I do not have the permission to provide it. You can obtain the raw data at https://marketscan.truvenhealth.com/marketscanportal/ and I've provided the processing script process_ccae.ipynb.
